name: Flutter APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Clean project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fitquest-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
